name: Build and push docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
      with:
        gcloud_service_key: ${{ secrets.GCR_KEY }}
        registry: eu.gcr.io
        project_id: awell-container-registry
        image_name: awell-extensions/custom-actions
        image_tag: latest, ${{ github.sha }}
        dockerfile: ./Dockerfile
        context: ./
